# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tf_testbed.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_inputImage = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_inputImage.setGeometry(QtCore.QRect(20, 10, 301, 301))
        self.groupBox_inputImage.setObjectName("groupBox_inputImage")
        self.label_inputImage = QtWidgets.QLabel(self.groupBox_inputImage)
        self.label_inputImage.setGeometry(QtCore.QRect(10, 30, 281, 261))
        self.label_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputImage.setObjectName("label_inputImage")
        self.groupBox_modelBuilder = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_modelBuilder.setGeometry(QtCore.QRect(330, 10, 661, 491))
        self.groupBox_modelBuilder.setObjectName("groupBox_modelBuilder")
        self.groupBox_library = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_library.setGeometry(QtCore.QRect(10, 20, 191, 121))
        self.groupBox_library.setObjectName("groupBox_library")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_library)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_library = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_library.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_library.setObjectName("verticalLayout_library")
        self.radioButton_tensorflow = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_tensorflow.setChecked(True)
        self.radioButton_tensorflow.setObjectName("radioButton_tensorflow")
        self.verticalLayout_library.addWidget(self.radioButton_tensorflow)
        self.radioButton_keras = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_keras.setObjectName("radioButton_keras")
        self.verticalLayout_library.addWidget(self.radioButton_keras)
        self.radioButton_pytorch = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_pytorch.setObjectName("radioButton_pytorch")
        self.verticalLayout_library.addWidget(self.radioButton_pytorch)
        self.groupBox_inputOutput = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_inputOutput.setGeometry(QtCore.QRect(210, 20, 251, 171))
        self.groupBox_inputOutput.setObjectName("groupBox_inputOutput")
        self.widget = QtWidgets.QWidget(self.groupBox_inputOutput)
        self.widget.setGeometry(QtCore.QRect(12, 33, 231, 131))
        self.widget.setObjectName("widget")
        self.gridLayout_inputOutput = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_inputOutput.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_inputOutput.setObjectName("gridLayout_inputOutput")
        self.label_inputSize = QtWidgets.QLabel(self.widget)
        self.label_inputSize.setObjectName("label_inputSize")
        self.gridLayout_inputOutput.addWidget(self.label_inputSize, 0, 0, 1, 1)
        self.spinBox_inputSize = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_inputSize.setFont(font)
        self.spinBox_inputSize.setMinimum(1)
        self.spinBox_inputSize.setMaximum(10000)
        self.spinBox_inputSize.setProperty("value", 784)
        self.spinBox_inputSize.setObjectName("spinBox_inputSize")
        self.gridLayout_inputOutput.addWidget(self.spinBox_inputSize, 0, 1, 1, 1)
        self.label_numClasses = QtWidgets.QLabel(self.widget)
        self.label_numClasses.setObjectName("label_numClasses")
        self.gridLayout_inputOutput.addWidget(self.label_numClasses, 1, 0, 1, 1)
        self.spinBox_numClasses = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_numClasses.setFont(font)
        self.spinBox_numClasses.setProperty("value", 10)
        self.spinBox_numClasses.setObjectName("spinBox_numClasses")
        self.gridLayout_inputOutput.addWidget(self.spinBox_numClasses, 1, 1, 1, 1)
        self.label_numLayers = QtWidgets.QLabel(self.widget)
        self.label_numLayers.setObjectName("label_numLayers")
        self.gridLayout_inputOutput.addWidget(self.label_numLayers, 2, 0, 1, 1)
        self.lineEdit_numLayers = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_numLayers.setReadOnly(True)
        self.lineEdit_numLayers.setObjectName("lineEdit_numLayers")
        self.gridLayout_inputOutput.addWidget(self.lineEdit_numLayers, 2, 1, 1, 1)
        self.label_modelName = QtWidgets.QLabel(self.widget)
        self.label_modelName.setObjectName("label_modelName")
        self.gridLayout_inputOutput.addWidget(self.label_modelName, 3, 0, 1, 1)
        self.lineEdit_modelName = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_modelName.setReadOnly(False)
        self.lineEdit_modelName.setObjectName("lineEdit_modelName")
        self.gridLayout_inputOutput.addWidget(self.lineEdit_modelName, 3, 1, 1, 1)
        self.groupBox_hiddenLayer = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_hiddenLayer.setGeometry(QtCore.QRect(10, 200, 451, 241))
        self.groupBox_hiddenLayer.setObjectName("groupBox_hiddenLayer")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_hiddenLayer)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 431, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_hiddenLayer = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_hiddenLayer.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_hiddenLayer.setObjectName("verticalLayout_hiddenLayer")
        self.horizontalLayout_FC = QtWidgets.QHBoxLayout()
        self.horizontalLayout_FC.setObjectName("horizontalLayout_FC")
        self.radioButton_FC = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_FC.setChecked(True)
        self.radioButton_FC.setObjectName("radioButton_FC")
        self.horizontalLayout_FC.addWidget(self.radioButton_FC)
        self.horizontalLayout_numNeurons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_numNeurons.setObjectName("horizontalLayout_numNeurons")
        self.label_numNeurons = QtWidgets.QLabel(self.layoutWidget1)
        self.label_numNeurons.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numNeurons.setObjectName("label_numNeurons")
        self.horizontalLayout_numNeurons.addWidget(self.label_numNeurons)
        self.spinBox_numNeurons = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_numNeurons.setMaximum(10000)
        self.spinBox_numNeurons.setProperty("value", 100)
        self.spinBox_numNeurons.setObjectName("spinBox_numNeurons")
        self.horizontalLayout_numNeurons.addWidget(self.spinBox_numNeurons)
        self.horizontalLayout_FC.addLayout(self.horizontalLayout_numNeurons)
        self.verticalLayout_hiddenLayer.addLayout(self.horizontalLayout_FC)
        self.horizontalLayout_CNN = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CNN.setObjectName("horizontalLayout_CNN")
        self.radioButton_CNN = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_CNN.setCheckable(True)
        self.radioButton_CNN.setChecked(False)
        self.radioButton_CNN.setObjectName("radioButton_CNN")
        self.horizontalLayout_CNN.addWidget(self.radioButton_CNN)
        self.gridLayout_CNN = QtWidgets.QGridLayout()
        self.gridLayout_CNN.setObjectName("gridLayout_CNN")
        self.label_kernelSize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_kernelSize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kernelSize.setObjectName("label_kernelSize")
        self.gridLayout_CNN.addWidget(self.label_kernelSize, 0, 0, 1, 1)
        self.label_kernelStride = QtWidgets.QLabel(self.layoutWidget1)
        self.label_kernelStride.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kernelStride.setObjectName("label_kernelStride")
        self.gridLayout_CNN.addWidget(self.label_kernelStride, 0, 1, 1, 1)
        self.label_numFilters = QtWidgets.QLabel(self.layoutWidget1)
        self.label_numFilters.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numFilters.setObjectName("label_numFilters")
        self.gridLayout_CNN.addWidget(self.label_numFilters, 0, 2, 1, 1)
        self.spinBox_kernelSize = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_kernelSize.setProperty("value", 3)
        self.spinBox_kernelSize.setObjectName("spinBox_kernelSize")
        self.gridLayout_CNN.addWidget(self.spinBox_kernelSize, 1, 0, 1, 1)
        self.spinBox_kernelStride = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_kernelStride.setProperty("value", 1)
        self.spinBox_kernelStride.setObjectName("spinBox_kernelStride")
        self.gridLayout_CNN.addWidget(self.spinBox_kernelStride, 1, 1, 1, 1)
        self.spinBox_numFilters = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_numFilters.setProperty("value", 1)
        self.spinBox_numFilters.setObjectName("spinBox_numFilters")
        self.gridLayout_CNN.addWidget(self.spinBox_numFilters, 1, 2, 1, 1)
        self.horizontalLayout_CNN.addLayout(self.gridLayout_CNN)
        self.verticalLayout_hiddenLayer.addLayout(self.horizontalLayout_CNN)
        self.horizontalLayout_actFn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_actFn.setObjectName("horizontalLayout_actFn")
        self.checkBox_actFn = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_actFn.setChecked(True)
        self.checkBox_actFn.setObjectName("checkBox_actFn")
        self.horizontalLayout_actFn.addWidget(self.checkBox_actFn)
        self.comboBox_actFn = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_actFn.setObjectName("comboBox_actFn")
        self.horizontalLayout_actFn.addWidget(self.comboBox_actFn)
        self.verticalLayout_hiddenLayer.addLayout(self.horizontalLayout_actFn)
        self.horizontalLayout_initFn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_initFn.setObjectName("horizontalLayout_initFn")
        self.checkBox_initFn = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_initFn.setObjectName("checkBox_initFn")
        self.horizontalLayout_initFn.addWidget(self.checkBox_initFn)
        self.comboBox_initFn = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_initFn.setObjectName("comboBox_initFn")
        self.horizontalLayout_initFn.addWidget(self.comboBox_initFn)
        self.verticalLayout_hiddenLayer.addLayout(self.horizontalLayout_initFn)
        self.horizontalLayout_maxDrop = QtWidgets.QHBoxLayout()
        self.horizontalLayout_maxDrop.setObjectName("horizontalLayout_maxDrop")
        self.checkBox_maxPooling = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_maxPooling.setObjectName("checkBox_maxPooling")
        self.horizontalLayout_maxDrop.addWidget(self.checkBox_maxPooling)
        self.gridLayout_maxPooling = QtWidgets.QGridLayout()
        self.gridLayout_maxPooling.setObjectName("gridLayout_maxPooling")
        self.spinBox_poolSize = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_poolSize.setProperty("value", 2)
        self.spinBox_poolSize.setObjectName("spinBox_poolSize")
        self.gridLayout_maxPooling.addWidget(self.spinBox_poolSize, 1, 0, 1, 2)
        self.spinBox_poolStride = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_poolStride.setProperty("value", 2)
        self.spinBox_poolStride.setObjectName("spinBox_poolStride")
        self.gridLayout_maxPooling.addWidget(self.spinBox_poolStride, 1, 2, 1, 1)
        self.label_poolStride = QtWidgets.QLabel(self.layoutWidget1)
        self.label_poolStride.setAlignment(QtCore.Qt.AlignCenter)
        self.label_poolStride.setObjectName("label_poolStride")
        self.gridLayout_maxPooling.addWidget(self.label_poolStride, 0, 2, 1, 1)
        self.label_poolSize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_poolSize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_poolSize.setObjectName("label_poolSize")
        self.gridLayout_maxPooling.addWidget(self.label_poolSize, 0, 0, 1, 2)
        self.horizontalLayout_maxDrop.addLayout(self.gridLayout_maxPooling)
        self.checkBox_dropOut = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_dropOut.setObjectName("checkBox_dropOut")
        self.horizontalLayout_maxDrop.addWidget(self.checkBox_dropOut)
        self.verticalLayout_keepProb = QtWidgets.QVBoxLayout()
        self.verticalLayout_keepProb.setObjectName("verticalLayout_keepProb")
        self.label_keepProb = QtWidgets.QLabel(self.layoutWidget1)
        self.label_keepProb.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keepProb.setObjectName("label_keepProb")
        self.verticalLayout_keepProb.addWidget(self.label_keepProb)
        self.doubleSpinBox_keepProb = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_keepProb.setDecimals(1)
        self.doubleSpinBox_keepProb.setMaximum(1.0)
        self.doubleSpinBox_keepProb.setSingleStep(0.1)
        self.doubleSpinBox_keepProb.setProperty("value", 0.7)
        self.doubleSpinBox_keepProb.setObjectName("doubleSpinBox_keepProb")
        self.verticalLayout_keepProb.addWidget(self.doubleSpinBox_keepProb)
        self.horizontalLayout_maxDrop.addLayout(self.verticalLayout_keepProb)
        self.verticalLayout_hiddenLayer.addLayout(self.horizontalLayout_maxDrop)
        self.pushButton_addLayer = QtWidgets.QPushButton(self.groupBox_modelBuilder)
        self.pushButton_addLayer.setGeometry(QtCore.QRect(360, 450, 101, 31))
        self.pushButton_addLayer.setObjectName("pushButton_addLayer")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_modelBuilder)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(470, 30, 181, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_modelViewer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_modelViewer.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_modelViewer.setObjectName("verticalLayout_modelViewer")
        self.scrollArea_modelViewer = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea_modelViewer.setWidgetResizable(True)
        self.scrollArea_modelViewer.setObjectName("scrollArea_modelViewer")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 177, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_modelViewer.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_modelViewer.addWidget(self.scrollArea_modelViewer)
        self.pushButton_buildModel = QtWidgets.QPushButton(self.groupBox_modelBuilder)
        self.pushButton_buildModel.setGeometry(QtCore.QRect(510, 450, 101, 31))
        self.pushButton_buildModel.setObjectName("pushButton_buildModel")
        self.groupBox_training = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_training.setGeometry(QtCore.QRect(540, 510, 321, 201))
        self.groupBox_training.setObjectName("groupBox_training")
        self.pushButton_trainModel = QtWidgets.QPushButton(self.groupBox_training)
        self.pushButton_trainModel.setGeometry(QtCore.QRect(210, 160, 101, 31))
        self.pushButton_trainModel.setObjectName("pushButton_trainModel")
        self.scrollArea_training = QtWidgets.QScrollArea(self.groupBox_training)
        self.scrollArea_training.setGeometry(QtCore.QRect(210, 30, 101, 121))
        self.scrollArea_training.setWidgetResizable(True)
        self.scrollArea_training.setObjectName("scrollArea_training")
        self.scrollAreaWidgetContents_training = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_training.setGeometry(QtCore.QRect(0, 0, 99, 119))
        self.scrollAreaWidgetContents_training.setObjectName("scrollAreaWidgetContents_training")
        self.textEdit_training = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_training)
        self.textEdit_training.setGeometry(QtCore.QRect(0, 0, 101, 121))
        self.textEdit_training.setObjectName("textEdit_training")
        self.scrollArea_training.setWidget(self.scrollAreaWidgetContents_training)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_training)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 191, 138))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_training = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_training.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_training.setObjectName("gridLayout_training")
        self.label_lossFn = QtWidgets.QLabel(self.layoutWidget2)
        self.label_lossFn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_lossFn.setObjectName("label_lossFn")
        self.gridLayout_training.addWidget(self.label_lossFn, 0, 0, 1, 1)
        self.comboBox_lossFn = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_lossFn.setObjectName("comboBox_lossFn")
        self.gridLayout_training.addWidget(self.comboBox_lossFn, 0, 1, 1, 1)
        self.label_optimizer = QtWidgets.QLabel(self.layoutWidget2)
        self.label_optimizer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_optimizer.setObjectName("label_optimizer")
        self.gridLayout_training.addWidget(self.label_optimizer, 1, 0, 1, 1)
        self.comboBox_optimizer = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_optimizer.setObjectName("comboBox_optimizer")
        self.gridLayout_training.addWidget(self.comboBox_optimizer, 1, 1, 1, 1)
        self.label_numEpochs = QtWidgets.QLabel(self.layoutWidget2)
        self.label_numEpochs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_numEpochs.setObjectName("label_numEpochs")
        self.gridLayout_training.addWidget(self.label_numEpochs, 2, 0, 1, 1)
        self.spinBox_numEpochs = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_numEpochs.setMaximum(100000)
        self.spinBox_numEpochs.setProperty("value", 10)
        self.spinBox_numEpochs.setObjectName("spinBox_numEpochs")
        self.gridLayout_training.addWidget(self.spinBox_numEpochs, 2, 1, 1, 1)
        self.label_batchSize = QtWidgets.QLabel(self.layoutWidget2)
        self.label_batchSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_batchSize.setObjectName("label_batchSize")
        self.gridLayout_training.addWidget(self.label_batchSize, 3, 0, 1, 1)
        self.spinBox_batchSize = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_batchSize.setMaximum(10000)
        self.spinBox_batchSize.setSingleStep(1)
        self.spinBox_batchSize.setProperty("value", 100)
        self.spinBox_batchSize.setObjectName("spinBox_batchSize")
        self.gridLayout_training.addWidget(self.spinBox_batchSize, 3, 1, 1, 1)
        self.label_batchSize_learningRate = QtWidgets.QLabel(self.layoutWidget2)
        self.label_batchSize_learningRate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_batchSize_learningRate.setObjectName("label_batchSize_learningRate")
        self.gridLayout_training.addWidget(self.label_batchSize_learningRate, 4, 0, 1, 1)
        self.lineEdit_learningRate = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_learningRate.setReadOnly(False)
        self.lineEdit_learningRate.setObjectName("lineEdit_learningRate")
        self.gridLayout_training.addWidget(self.lineEdit_learningRate, 4, 1, 1, 1)
        self.groupBox_evaluation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_evaluation.setGeometry(QtCore.QRect(870, 510, 121, 151))
        self.groupBox_evaluation.setObjectName("groupBox_evaluation")
        self.pushButton_evaluation = QtWidgets.QPushButton(self.groupBox_evaluation)
        self.pushButton_evaluation.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.pushButton_evaluation.setObjectName("pushButton_evaluation")
        self.pushButton_prediction = QtWidgets.QPushButton(self.groupBox_evaluation)
        self.pushButton_prediction.setGeometry(QtCore.QRect(10, 110, 101, 31))
        self.pushButton_prediction.setObjectName("pushButton_prediction")
        self.pushButton_loadModel = QtWidgets.QPushButton(self.groupBox_evaluation)
        self.pushButton_loadModel.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.pushButton_loadModel.setObjectName("pushButton_loadModel")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(880, 670, 101, 31))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.groupBox_plotPrediction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_plotPrediction.setGeometry(QtCore.QRect(20, 320, 301, 221))
        self.groupBox_plotPrediction.setObjectName("groupBox_plotPrediction")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_plotPrediction)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 281, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_plotPrediction = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_plotPrediction.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_plotPrediction.setObjectName("horizontalLayout_plotPrediction")
        self.scrollArea_log = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_log.setGeometry(QtCore.QRect(330, 520, 201, 191))
        self.scrollArea_log.setWidgetResizable(True)
        self.scrollArea_log.setObjectName("scrollArea_log")
        self.scrollAreaWidgetContents_log = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_log.setGeometry(QtCore.QRect(0, 0, 199, 189))
        self.scrollAreaWidgetContents_log.setObjectName("scrollAreaWidgetContents_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_log)
        self.textEdit_log.setGeometry(QtCore.QRect(0, 0, 201, 191))
        self.textEdit_log.setObjectName("textEdit_log")
        self.scrollArea_log.setWidget(self.scrollAreaWidgetContents_log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MNIST Testbed"))
        self.groupBox_inputImage.setTitle(_translate("MainWindow", "Input image"))
        self.label_inputImage.setText(_translate("MainWindow", "MNIST image"))
        self.groupBox_modelBuilder.setTitle(_translate("MainWindow", "Model Builder"))
        self.groupBox_library.setTitle(_translate("MainWindow", "Library"))
        self.radioButton_tensorflow.setText(_translate("MainWindow", "TensorFlow"))
        self.radioButton_keras.setText(_translate("MainWindow", "Keras (TF backend)"))
        self.radioButton_pytorch.setText(_translate("MainWindow", "PyTorch"))
        self.groupBox_inputOutput.setTitle(_translate("MainWindow", "Input / Output"))
        self.label_inputSize.setText(_translate("MainWindow", "Input size (1D vector)"))
        self.label_numClasses.setText(_translate("MainWindow", "# of classes"))
        self.label_numLayers.setText(_translate("MainWindow", "# of hidden layers"))
        self.lineEdit_numLayers.setText(_translate("MainWindow", "0 layer"))
        self.label_modelName.setText(_translate("MainWindow", "Model name"))
        self.lineEdit_modelName.setText(_translate("MainWindow", "model"))
        self.groupBox_hiddenLayer.setTitle(_translate("MainWindow", "Hidden Layer Parameters"))
        self.radioButton_FC.setText(_translate("MainWindow", "Fully-connected layer"))
        self.label_numNeurons.setText(_translate("MainWindow", "# of neurons"))
        self.radioButton_CNN.setText(_translate("MainWindow", "2D Convolution layer"))
        self.label_kernelSize.setText(_translate("MainWindow", "Kernel"))
        self.label_kernelStride.setText(_translate("MainWindow", "Stride"))
        self.label_numFilters.setText(_translate("MainWindow", "# of filters"))
        self.checkBox_actFn.setText(_translate("MainWindow", "Activation function"))
        self.checkBox_initFn.setText(_translate("MainWindow", "Weight Initializer function"))
        self.checkBox_maxPooling.setText(_translate("MainWindow", "Max pooling"))
        self.label_poolStride.setText(_translate("MainWindow", "Stride"))
        self.label_poolSize.setText(_translate("MainWindow", "Kernel"))
        self.checkBox_dropOut.setText(_translate("MainWindow", "Dropout"))
        self.label_keepProb.setText(_translate("MainWindow", "Keep_prob"))
        self.pushButton_addLayer.setText(_translate("MainWindow", "Add layer"))
        self.pushButton_buildModel.setText(_translate("MainWindow", "Build model"))
        self.groupBox_training.setTitle(_translate("MainWindow", "Training"))
        self.pushButton_trainModel.setText(_translate("MainWindow", "Train model"))
        self.label_lossFn.setText(_translate("MainWindow", "Loss function"))
        self.label_optimizer.setText(_translate("MainWindow", "Optimizer"))
        self.label_numEpochs.setText(_translate("MainWindow", "# of Epochs"))
        self.label_batchSize.setText(_translate("MainWindow", "Batch size"))
        self.label_batchSize_learningRate.setText(_translate("MainWindow", "Learning rate"))
        self.lineEdit_learningRate.setText(_translate("MainWindow", "0.001"))
        self.groupBox_evaluation.setTitle(_translate("MainWindow", "Evaluation"))
        self.pushButton_evaluation.setText(_translate("MainWindow", "Evaluation"))
        self.pushButton_prediction.setText(_translate("MainWindow", "Prediction"))
        self.pushButton_loadModel.setText(_translate("MainWindow", "Load model"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.groupBox_plotPrediction.setTitle(_translate("MainWindow", "Prediction"))

